
version: 2

models:  
  - name: dim_product
    columns:
      - name: product_key
        tests:
          - unique
          - not_null

  - name: dim_customer
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
      
      - name: address_key
        tests:
          - relationships:
              to: ref('dim_address')
              field: address_key

  - name: dim_address
    columns:
      - name: address_key
        tests:
          - unique
          - not_null
  
  - name: dim_order
    columns:
      - name: order_key
        test:
          - unique
          - not_null

  - name: fact_sales
    columns:
      - name: order_key
        tests:
          - relationships:
              to: ref('dim_order')
              field: order_key

      - name: customer_key
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_key

      - name: product_key
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_key
      
  


